### ISSUE TITLE
The validateEnvironment function requires more than is needed.

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/crowdin-action#45]
**Describe the bug**

Trying to run the `pull-request` plugin, and only gave it the env variables specified: `GH_TOKEN`, `BRANCH`, `REPOSITORY`, `BASE`, `TITLE`, `BODY` - it gave me an error: ["Missing Crowdin credentials."](https://github.com/freeCodeCamp/i18n-curriculum/actions/runs/10051339299/job/27780769938) It looks like the [validateEnvironment function](https://github.com/freeCodeCamp/crowdin-action/blob/96c35ec5530a743cd30ff46781fb864fc9213233/src/utils/validate-environment.ts) wants `CROWDIN_PERSONAL_TOKEN` and `CROWDIN_API_URL` - but the plugin doesn't use those as far as I can tell. Seems like the validation should only require the things necessary for the plugin. I may be missing something, but I think that's accurate.

**Comment by naomi-lgbt** [comment]
> The following environment variables are required to be set in order to run the actions, regardless of which plugin is chosen.

> CROWDIN_PERSONAL_TOKEN, CROWDIN_API_URL, PROJECT_ID, and PLUGIN. Note that PLUGIN should match one of the options below.

**Comment by naomi-lgbt** [comment]
It's a top-level check.

**Comment by moT01** [comment]
K. If we want to keep it that way - we can just close this.

**Comment by naomi-lgbt** [comment]
IMHO it makes sense, simply because so many of the plugins rely on those values.
